import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { RootClientPage } from "./RootClientPage";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-stretch  w-full h-screen overflow-y-clip max-h-screen">
          <RootClientPage>{children}</RootClientPage>
        </main>
      </body>
    </html>
  );
}
